### ISSUE TITLE
Sidnavbar Breite

### ISSUE THREAD

**Issue by matthimilian** [hfg-gmuend/hfg-documentation-generator#10]
Hey, 
wenn Subpages ebenfalls Subpages besitzen werden deren Titel in der Sidebar entweder getrennt oder abgeschnitten. Könnte hier eine anpassung der Breite der Sidebar in Betracht gezogen werden? 
Über die CSS ist leider kein einfacher Workaround von meiner Seite aus möglich. 

Danke schonmals
Grüße Joni

**Comment by phytrisha** [comment]
Could you provide a screenshot, where the problem is visible? Thanks!

**Comment by matthimilian** [comment]
Of course 
![subpage](https://user-images.githubusercontent.com/47104669/51841764-a1f23f00-230f-11e9-8318-1fcc3b75b657.JPG)

**Comment by b-g** [comment]
Hi @PaulRaschke, could you have a look on this? Do you know a quick fix (either less line spacing, or text-overflow: ellipsis)?

**Comment by PaulRaschke** [comment]
Hi @b-g,

I've looked into it, but didn't find a nice quick fix.
The Layout was originally conceived for just one layer of subpages. A possibility would be to use hyphenation, but then a js-library is necessary. Sadly CSS `hyphens: auto` seems to only work with Firefox.
And `text-overflow: ellipsis` doesn't work for multilines.
To avoid that the text is cut-off on big displays with enough space on the right the overflow can be set to visible, but that wouldn't fix the problem for smaller window sizes.
But I think less line spacing would be useful nevertheless, because now it seems like there are 4 subchapters instead of 2.

What do you mean @b-g?

**Comment by b-g** [comment]
@PaulRaschke @bohnacker 

I think we should keep it simple and limit the sub pages to a max level of 2. After reviewing documentations of 4 entire semesters ... I had this edge case of level 3 exactly a single time.
