### ISSUE TITLE
First time viewing of a page is very slow (and sometimes brings the server to crash)

### ISSUE THREAD

**Issue by bohnacker** [hfg-gmuend/hfg-documentation-generator#11]
This seems to be caused by kirby⁩/vendor⁩/getkirby⁩/toolkit⁩/vendors⁩/abeautifulsite⁩/SimpleImage.php which might be responsible for resizing images.

When I remove this line in config.php, it gets a lot faster.  
`c::set("image.widths", [480, 854, 1280, 1920, 2560]);`

Why is this line needed? And why are image.widths used when `image.resize_on_upload` is `false`?

**Comment by b-g** [comment]
This is because the very first time Kirby generates the images for retina / responsive images into the thumbnails folder. Once the images are generated everything should be fine.

You can also increase the php memory footprint e.g. `memory_limit = 512M` in 
https://github.com/hfg-gmuend/hfg-documentation-generator/blob/46d361cd5fec4cb689a75fb1351f80ce25cc63a8/_local-dev-php.ini#L3

@PaulRaschke right?

**Comment by PaulRaschke** [comment]
Hi @b-g and @bohnacker,

> This is because the very first time Kirby generates the images for retina / responsive images into the thumbnails folder. Once the images are generated everything should be fine.

That's correct.
The `image.resize_on_upload` option determines if uploaded images which exceed the maximum defined file size for images and the maximum defined width in `image.widths` will be resized to match the maximum defined image width in `image.widths`. The option is turned off by default because it was considered to be unnecessary and the resize function doesn't guarantee that resized images don't exceed the maximum defined file size for images.

**Comment by b-g** [comment]
@PaulRaschke Thanks for the infos!

I actually would vote to put back the `image.resize_on_upload` as dealing with 2GB Programmiertes Entwerfen 1 Dokus is not fun :) I think a max width of 1920 * 2 = `3840 px` should be enough.
