### ISSUE TITLE
First two pictures are smaller, but everything is set on size half

### ISSUE THREAD

**Issue by SonjaBre** [hfg-gmuend/hfg-documentation-generator#16]
[content.zip](https://github.com/hfg-gmuend/hfg-documentation-generator/files/3285903/content.zip)

Wie mit Hartmut schon besprochen: In meiner Unterseite "Darstellung mit Punkten" werden die ersten beiden Bilder kleiner dargestellt, obwohl sie genau gleich groß sind und alle auf size: half gestellt wurden.

**Comment by bohnacker** [comment]
@PaulRaschke could you please help with that. Below is a screenshot of the problem. The first two images with 'size: half' are not displayed correctly because the second one gets the class 'image first' but should be 'image last'. I can't figure out what to change in site/tags/image.php.

<img width="1125" alt="Bildschirmfoto 2019-06-14 um 14 41 09" src="https://user-images.githubusercontent.com/2828139/59509905-a0867500-8eb2-11e9-9d00-55febab5905d.png">
