### ISSUE TITLE
User accounts: force giving first and last name

### ISSUE THREAD

**Issue by bohnacker** [hfg-gmuend/hfg-documentation-generator#25]
It seems to be possible to get around giving your user account a first and last name:
<img width="1074" alt="Bildschirmfoto 2020-03-23 um 12 05 09" src="https://user-images.githubusercontent.com/2828139/77310645-f2401380-6cfe-11ea-8705-ef95d7ee9688.png">

This should be mandatory, otherwise pages might look like that (see the empty arrow):
<img width="908" alt="Bildschirmfoto 2020-03-23 um 12 06 08" src="https://user-images.githubusercontent.com/2828139/77312392-341e8900-6d02-11ea-90fe-748f4179df6f.png">

**Comment by PaulRaschke** [comment]
This doesn't happen if the account is created automatically after a successful HfG-Mailserver login.
Nevertheless, the fields can be made required so that students cannot leave the fields empty. If this is desired, the default values for the fields 'firstName' and 'lastName' when automatically creating a new user after a successful HfG-Mailserver login most likely must not be empty, as implemented [here](https://github.com/hfg-gmuend/hfg-documentation-generator/blob/22b005bac1f924ed0c0ba1e37b7df1a5aa63f474/site/plugins/panel-extensions/customLogin/index.php#L64-L67). So maybe "undefined" should be used as default string.

**Comment by bohnacker** [comment]
Ok, thanks @PaulRaschke for the explanation. I'm not sure if I understood completely what's most likely coming from the HfG mail server. But I think we should not bother about this to much. The students will want to have their names displayed correctly.

**Comment by bohnacker** [comment]
We'll keep it as is. This should not be a (common) problem.
