### ISSUE TITLE
Can't create sub pages of chapters in Kirby admin area

### ISSUE THREAD

**Issue by b-g** [hfg-gmuend/hfg-documentation-generator#8]
Hi @PaulRaschke, Hope all is going well! We started to use the Kirby hfg-documentation-generator in several courses ... works like a charm so far, even on Windows :) We just found this small bug:

Currently the `+ Add` subpage button is missing for pages of type Chapter, see screenshot.

Could you have a look?

![2018-12-12 at 14 36](https://user-images.githubusercontent.com/480224/49873125-63fe9180-fe1b-11e8-93ed-a0c5b81e376d.png)

**Comment by PaulRaschke** [comment]
Hi @b-g. Great to hear that the hfg-documentation-generator is used.
I fixed the bug, sorry for the inconvinience. Tested it so many times but missed something so important. Typical 🙈

The problem was the defined max page depth. I changed it so it can be defined in the config now.

See:
https://github.com/hfg-gmuend/hfg-documentation-generator/commit/a13c8f8d6a830abe9427f7a6e851e4ff834be27b

**Comment by b-g** [comment]
Hi @PaulRaschke, Many thanks 🙏 + Perfect! Wasn't aware of this setting. Yes ... really exciting to see a lot of people using the generator. So far it goes really well! Thanks again for all the good work! Happy 🎄, Bene
